# Generated by Django 4.0.5 on 2022-07-28 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('seat', models.CharField(choices=[('Governor', 'governor'), ('Dgovernor', 'dgovernor'), ('Senate', 'senate'), ('Mp', 'mp'), ('Mca', 'mca'), ('Wrep', 'wrep')], default='Governor', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const', models.CharField(max_length=20)),
                ('ward', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('pstation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=20)),
                ('const', models.CharField(max_length=20)),
                ('ward', models.CharField(max_length=20)),
                ('centre', models.CharField(max_length=20)),
                ('voters', models.IntegerField()),
                ('pstation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcast', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('aspirant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.aspirant')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.station')),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='sub_county',
        ),
        migrations.RemoveField(
            model_name='county',
            name='date_created',
        ),
        migrations.DeleteModel(
            name='Election',
        ),
        migrations.DeleteModel(
            name='Leaders',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='SubCounty',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
        migrations.AddField(
            model_name='station',
            name='County',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.county'),
        ),
    ]
