# Generated by Django 4.0.5 on 2022-07-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_aspirant_station_upload_vote_remove_location_ward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='pstation',
            field=models.IntegerField(),
        ),
    ]
