# Generated by Django 4.0.5 on 2022-07-29 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_alter_station_pstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='pstation',
        ),
    ]
