# Generated by Django 4.0.5 on 2022-07-29 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_remove_station_pstation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='County',
            new_name='county',
        ),
    ]
