# Generated by Django 4.0.5 on 2022-08-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0006_rename_county_station_county'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='centre',
            new_name='center',
        ),
    ]
