# Generated by Django 4.0.5 on 2022-08-04 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0008_alter_upload_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='county',
        ),
        migrations.AlterField(
            model_name='vote',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.upload'),
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='Station',
        ),
    ]
