# Generated by Django 4.0.5 on 2022-08-05 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0009_remove_station_county_alter_vote_station_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.aspirant')),
            ],
        ),
        migrations.CreateModel(
            name='Votecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.user')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.vote')),
            ],
        ),
        migrations.AlterField(
            model_name='aspirant',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc.seat'),
        ),
    ]
